import re as r
import copy

NodeReg=r'".*?"\s*\[.*?\]'
NodeReg_Label=r'label=".*?"'
NodeReg_Head=r'^".*?"'
EdgeReg=r'".*?"\s*->\s*".*?"'


def preprocess(Path):
    '''
    :param Path: Preprocessing DOT file generated by SWEET
    :return: Dot Data that suit networkx
    '''
    Input=open(Path,'r')
    Output=open(Path+'tmp','w')
    Definition=''

    #step1 生成对应label转换表,查找definition
    DefinitionDict={}
    try:
        while True:
            line=Input.readline()
            if line.strip()!='':
                line=line.strip()
                if r.match(NodeReg,line) or r.match(EdgeReg,line):
                    Definition=Definition+line+'\n'
                    if r.match(NodeReg,line):
                        #生成表
                        head=r.search(NodeReg_Head,line).group()
                        label=r.search(NodeReg_Label,line).group().split('=')[-1]
                        DefinitionDict[head]=label
                else:
                    continue
            else:
                break

        #step 2 修改definition

        for key in DefinitionDict.keys():
            if DefinitionDict[key]!='""':
                # entry exit 没有label名字
                Definition=Definition.replace(key,DefinitionDict[key])
            else:
                continue


        #step 3 子图中保留结点

        Input.seek(0)
        # flag -> True , put Definition
        Flag=False
        while True:
            line=Input.readline()
            if line.strip().startswith('subgraph') and Flag==False:
                Flag=True
                Output.write(Definition)
            if line.strip()!='':
                line=line.strip()
                if r.match(NodeReg,line) or r.match(EdgeReg,line):
                    #留结点声明,改label,label为空的就不换了
                    if r.match(NodeReg,line):
                        label=r.search(NodeReg_Label,line)
                        label_name=label.group().split('=')[-1]
                        if label_name!='""':
                            Output.write(label_name+'\n')
                        else:
                            Output.write(r.search(NodeReg_Head,line).group()+'\n')
                    pass
                else:
                    Output.write(line+'\n')
            else:
                break

    except:
        print('Preprocessing Error.')
        exit(-1)
    finally:
        Input.close()
        Output.close()